objects/PS_Group_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Carousel_Caption__c</fullName>
        <inlineHelpText>The header can be no more than 150 characters (including spaces)</inlineHelpText>
        <label>Header</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carousel_Description__c</fullName>
        <inlineHelpText>The sub-header can be no more than 250 characters (including spaces)</inlineHelpText>
        <label>Sub-Header</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_URL__c</fullName>
        <inlineHelpText>URL must start with http://. If this a Video the url must be an EMBEDDED video link.</inlineHelpText>
        <label>External URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature_Carousel_Sort_Order__c</fullName>
        <inlineHelpText>The lower the value the earlier the slide shows up in the carousel</inlineHelpText>
        <label>Sort Order</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Expired__c</fullName>
        <formula>IF( 
AND(!ISNULL(Expiration_Date__c),!ISNULL(Start_Date__c)), OR(TODAY() &gt; Expiration_Date__c, TODAY() &lt; Start_Date__c),
IF( AND(ISNULL(Expiration_Date__c),!ISNULL(Start_Date__c)), TODAY() &lt; Start_Date__c,
IF( AND(!ISNULL(Expiration_Date__c),ISNULL(Start_Date__c)), TODAY() &gt; Expiration_Date__c,
IF( AND(ISNULL(Expiration_Date__c),ISNULL(Start_Date__c)), false, false) 
)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Resource_Grouping_Name__c</fullName>
        <label>Resource Grouping Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Slider_Url_c__c</fullName>
        <label>Slider Url</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>PS Group Resource</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Group Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CarouselHelper.cls
/**
 * @author anthony.beran@slalom.com
 * @date 6/20/18
 * @version 1.0
 * @description CarouselHelper helper class for PS_Group_Resource__c edit functionality
 */

public with sharing class CarouselHelper {

    /**
     * @author anthony.beran@slalom.com
     * @date 07/05/18
     * @version 1.0
     * @description Returns list of decorator objects for PS_Group_Resource__c
     *
     * @param records
     *
     * @return List<CarouselHelper.slideDecorator>
     */
    public static List<CarouselHelper.slideDecorator> getRecords(List<Id> records) {
        List<PS_Group_Resource__c> resources = new List<PS_Group_Resource__c>();
        List<ContentDocumentLink> contentDocumentLinks = new List<ContentDocumentLink>();

        resources = [
            SELECT Carousel_Caption__c, Carousel_Description__c, Expiration_Date__c, External_URL__c, Feature_Carousel_Sort_Order__c, Slider_Url_c__c, Is_Expired__c, Description__c, Resource_Grouping_Name__c
            FROM PS_Group_Resource__c
            WHERE Id IN :records
            ORDER BY Feature_Carousel_Sort_Order__c ASC
        ];

        //test
        if ( !records.isEmpty() ) {
            contentDocumentLinks = [
                SELECT LinkedEntityId, ContentDocument.LatestPublishedVersionId
                FROM ContentDocumentLink
                WHERE LinkedEntityId IN :records
            ];
        }


        Map<Id, CarouselHelper.slideDecorator> slides = new Map<Id, CarouselHelper.slideDecorator>();
        for ( PS_Group_Resource__c r : resources ) {
            slides.put(r.Id, new CarouselHelper.slideDecorator(r));
        }

        for ( ContentDocumentLink c : contentDocumentLinks ) {
            if ( null != c.LinkedEntityId ) {
                String url = CommunityHelper.getSiteUrl() + BMGF_Resource_Helper.FILE_URL_PREFIX + c.ContentDocument.LatestPublishedVersionId;
                slides.get(c.LinkedEntityId).setImgUrl(url);
                break;
            }
        }

        return slides.values();
    }

    @TestVisible
    private class slideDecorator {
        PS_Group_Resource__c resource;
        public Id id;
        public String caption;
        public String description;
        public Date expiration;
        public String externalUrl;
        public Decimal sortOrder;
        public String url;
        public String imgUrl;
        public Boolean isExpired;

        public slideDecorator(PS_Group_Resource__c resource) {
            this.resource = resource;
            this.id = resource.Id;
            this.caption = resource.Carousel_Caption__c;
            this.description = resource.Carousel_Description__c;
            this.expiration = resource.Expiration_Date__c;
            this.externalUrl = resource.External_URL__c;
            this.sortOrder = resource.Feature_Carousel_Sort_Order__c;
            this.url = resource.Slider_Url_c__c;
            this.isExpired = resource.Is_Expired__c;
        }

        public void setImgUrl(String imgUrl) {
            this.imgUrl = imgUrl;
        }
    }
}